package com.example.slices.models;

import com.example.slices.controllers.DBConnector;
import com.example.slices.testing.DebugLogger;
import com.example.slices.interfaces.DBWriteCallback;
import com.example.slices.interfaces.EntrantCallback;
import com.example.slices.interfaces.EntrantIDCallback;
import com.example.slices.interfaces.EntrantListCallback;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * Entrant class for storing entrant information
 *
 */
public class Entrant {
    /**
     * Name of the entrant
     */
    private String name;
    /**
     * Email of the entrant, may be null
     */
    private String email;
    /**
     * Phone number of the entrant, may be null
     */
    private String phoneNumber;
    /**
     * ID of the entrant, generated by the database
     */
    private int id;
    /**
     * Device ID of the entrant, generated by the device
     */
    private String deviceId;
    /**
     * List of confirmed events of the entrant
     * Disabled due to cycle
     */
    //private List<Event> confirmedEvents;
    /**
     * List of waitlisted events of the entrant
     * Disabled due to cycle
     */
    //private List<Event> waitlistedEvents;
    /**
     * Parent of the entrant, 0 if entrant is a primary entrant
     */
    private int parent = 0;

    /**
     * Database connector for the entrant
     */
    private final DBConnector db = new DBConnector();
    /**
     * List of sub-entrants of the entrant
     */
    private List<Integer> subEntrants;

    /**
     * Default constructor for the Entrant class, need for serialization
     */
    public Entrant() {}

    /**
     * Test constructor for the Entrant class
     * @param name
     *      Name of the entrant
     * @param email
     *      Email of the entrant
     * @param phoneNumber
     *      Phone number of the entrant
     * @param id
     *      ID of the entrant
     */
    public Entrant(String name, String email, String phoneNumber, int id) {
        this.name = name;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.id = id;
        this.subEntrants = new ArrayList<>();
    }

    /**
     * Primary constructor for the Entrant class for creating a primary entrant
     * @param deviceId
     *      Device ID of the entrant
     * @param callback
     *      Callback for when the entrant is created
     */
    public Entrant(String deviceId, EntrantCallback callback) {
        this.deviceId = deviceId;
        this.subEntrants = new ArrayList<Integer>();

        db.getNewEntrantId(new EntrantIDCallback() {
            @Override
            public void onSuccess(int id) {
                Entrant.this.id = id;
                db.writeEntrant(Entrant.this, new DBWriteCallback() {
                    @Override
                    public void onSuccess() {
                        DebugLogger.d("Entrant", "Entrant created successfully");
                        callback.onSuccess(Entrant.this);
                    }

                    @Override
                    public void onFailure(Exception e) {
                        DebugLogger.d("Entrant", "Entrant creation failed");
                        callback.onFailure(e);
                    }
                });
            }

            @Override
            public void onFailure(Exception e) {
                DebugLogger.d("Entrant", "Entrant creation failed");
            }
        });

    }


    /**
     * Constructor for the Entrant class for creating a primary entrant
     * @param name
     *      Name of the entrant
     * @param email
     *      Email of the entrant
     * @param phoneNumber
     *      Phone number of the entrant
     * @param callback
     *      Callback for when the entrant is created
     */

    public Entrant(String name, String email, String phoneNumber, EntrantCallback callback) {
        this.name = name;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.subEntrants = new ArrayList<Integer>();
        db.getNewEntrantId(new EntrantIDCallback() {
            @Override
            public void onSuccess(int id) {
                Entrant.this.id = id;
                db.writeEntrant(Entrant.this, new DBWriteCallback() {
                    @Override
                    public void onSuccess() {
                        DebugLogger.d("Entrant", "Entrant created successfully");
                        callback.onSuccess(Entrant.this);
                    }

                    @Override
                    public void onFailure(Exception e) {
                        DebugLogger.d("Entrant", "Entrant creation failed");
                        callback.onFailure(e);
                    }
                });
            }

            @Override
            public void onFailure(Exception e) {
                DebugLogger.d("Entrant", "Entrant creation failed");
            }
        });
    }


    /**
     * Constructor for the Entrant class for creating a secondary entrant
     * INCOMPLETE!!
     * @param name
     *      Name of the entrant
     * @param email
     *      Email of the entrant
     * @param phoneNumber
     *      Phone number of the entrant
     * @param parent
     *      Parent of the entrant
     */
    public Entrant(String name, String email, String phoneNumber, Entrant parent, EntrantCallback callback) {
        if (parent.parent != 0 ) {
            throw new IllegalArgumentException("Cant have parent with parent");
        }

        this.name = name;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.subEntrants = null;
        db.getNewEntrantId(new EntrantIDCallback() {
            @Override
            public void onSuccess(int id) {
                Entrant.this.id = id;
                db.writeEntrant(Entrant.this, new DBWriteCallback() {
                    @Override
                    public void onSuccess() {
                        DebugLogger.d("Entrant", "Entrant created successfully");
                        parent.addSubEntrant(Entrant.this);
                        db.updateEntrant(parent, new DBWriteCallback() {
                            @Override
                            public void onSuccess() {
                                DebugLogger.d("Entrant", "Parent updated successfully");
                                Entrant.this.parent = parent.getId();
                                callback.onSuccess(Entrant.this);

                            }

                            @Override
                            public void onFailure(Exception e) {
                                DebugLogger.d("Entrant", "Parent update failed");
                            }
                        });

                    }

                    @Override
                    public void onFailure(Exception e) {
                        DebugLogger.d("Entrant", "Entrant write failed");
                    }
                });
            }
            public void onFailure(Exception e) {
                DebugLogger.d("Entrant", "Entrant creation failed");
            }
        });

    }

    /**
     * Getter for the device ID of the entrant
     * @return
     *      Device ID of the entrant
     */
    public String getDeviceId() {
        return deviceId;
    }
    /**
     * Getter for the name of the entrant
     * @return
     *      Name of the entrant
     */
    public String getName() {
        return name;
    }
    /**
     * Getter for the email of the entrant
     * @return
     *      Email of the entrant
     */
    public String getEmail() {
        return email;
    }
    /**
     * Getter for the phone number of the entrant
     * @return
     *      Phone number of the entrant
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }
    /**
     * Getter for the ID of the entrant
     * @return
     *      ID of the entrant
     */
    public int getId() {
        return id;
    }
    /**
     * Getter for the list of sub entrant ids of the entrant
     * @return
     *      List of sub entrant ids of the entrant
     */
    public List<Integer> getSubEntrants() {
        return subEntrants;
    }
    /**
     * Getter for the list of confirmed events of the entrant
     * @return
     *      List of confirmed events of the entrant
     */
    //ublic List<Event> getConfirmedEvents() {
        //return confirmedEvents;

    //}
    /**
     * Getter for the list of waitlisted events of the entrant
     * @return
     *      List of waitlisted events of the entrant
     */
    //public List<Event> getWaitlistedEvents() {
        //return waitlistedEvents;

    //}

    /**
     * Getter for the parent of the entrant
     * @return
     *      Parent of the entrant
     */
    public int getParent() {
        return parent;
    }

    /**
     * Setter for the name of the entrant
     * @param name
     *      Name of the entrant
     */
    public void setName(String name) {
        this.name = name;

    }
    /**
     * Setter for the email of the entrant
     * @param email
     *      Email of the entrant
     */
    public void setEmail(String email) {
        this.email = email;

    }
    /**
     * Setter for the phone number of the entrant
     * @param phoneNumber
     *      Phone number of the entrant
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;

    }
    /**
     * Setter for the ID of the entrant
     * @param id
     *      ID of the entrant
     */
    public void setId(int id) {
        this.id = id;

    }

    /**
     * Setter for the list of confirmed events of the entrant
     * @param events
     *      List of confirmed events of the entrant
     */
    //public void setConfirmedEvents(List<Event> events) {
        //this.confirmedEvents = events;

    //}
    /**
     * Setter for the list of waitlisted events of the entrant
     * @param events
     *      List of waitlisted events of the entrant
     */
    //public void setWaitlistedEvents(List<Event> events) {
        //this.waitlistedEvents = events;

    //}


    /**
     * Adds a sub entrant to the list of sub entrants of the entrant
     * INCOMPLETE!!
     * @param child
     *      Sub entrant to add
     *
     */
    public void addSubEntrant(Entrant child) {
        subEntrants.add(child.getId());
    }


    /**
     * Gets the sub entrants of the entrant
     * @param callback
     *      Callback for when the sub entrants are retrieved
     */
    public void getSubEntrants(EntrantListCallback callback) {
        List<Entrant> retSubEntrants = new ArrayList<>();
        for (int i = 0; i < this.subEntrants.size(); i++) {
            int idToGet = this.subEntrants.get(i);
            db.getEntrant(idToGet, new EntrantCallback() {
                @Override
                public void onSuccess(Entrant entrant) {
                    retSubEntrants.add(entrant);

                    if (retSubEntrants.size() == Entrant.this.subEntrants.size()) {
                        callback.onSuccess(retSubEntrants);
                    }
                }

                @Override
                public void onFailure(Exception e) {
                    callback.onFailure(e);
                }
            });
        }

    }

    public void getParent(EntrantCallback callback) {
        //Get the parent of the entrant
        db.getEntrant(this.parent, new EntrantCallback() {
            @Override
            public void onSuccess(Entrant entrant) {
                callback.onSuccess(entrant);
            }

            @Override
            public void onFailure(Exception e) {
                callback.onFailure(e);
            }
        });

    }



    /**
     * Checks if two entrants are equal
     * @param o
     *      Object to compare to
     * @return
     *      True if the objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Entrant entrant = (Entrant) o;
        return id == entrant.id; // or whatever uniquely identifies an Entrant
    }
    /**
     * Generates a hash code for the entrant
     * @return
     *      Hash code for the entrant
     */
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }



}
