package com.example.slices.models;


import com.example.slices.controllers.EntrantController;
import com.example.slices.interfaces.ProfileChangeListener;
import com.example.slices.testing.DebugLogger;
import com.example.slices.interfaces.DBWriteCallback;
import com.example.slices.interfaces.EntrantCallback;
import com.example.slices.interfaces.EntrantIDCallback;
import com.example.slices.interfaces.EntrantListCallback;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * @author Ryan Haubrich
 * @version 1.0
 * Entrant class for storing entrant information
 *
 */
public class Entrant {

    private Profile profile;

    private int id;
    /**
     * Device ID of the entrant, generated by the device
     */
    private String deviceId;


    private int parent = 0;


    /**
     * List of sub-entrants of the entrant
     */
    private List<Integer> subEntrants;

    private List<Integer> organizedEvents;


    /**
     * Default constructor for the Entrant class, need for serialization
     */
    public Entrant() {}

    /**
     * Test constructor for the Entrant class
     * @param name
     *      Name of the entrant
     * @param email
     *      Email of the entrant
     * @param phoneNumber
     *      Phone number of the entrant
     * @param id
     *      ID of the entrant
     */
    public Entrant(String name, String email, String phoneNumber, int id) {
        this.profile = new Profile(name, email, phoneNumber, true, id);
        this.id = id;
        this.subEntrants = new ArrayList<>();
    }

    /**
     * Primary constructor for the Entrant class for creating a primary entrant
     * @param deviceId
     *      Device ID of the entrant
     * @param callback
     *      Callback for when the entrant is created
     */
    public Entrant(String deviceId, EntrantCallback callback) {
        this.deviceId = deviceId;
        this.subEntrants = new ArrayList<Integer>();

        EntrantController.getNewEntrantId(new EntrantIDCallback() {
            @Override
            public void onSuccess(int id) {
                Entrant.this.id = id;
                Entrant.this.profile = new Profile(id);
                EntrantController.writeEntrant(Entrant.this, new DBWriteCallback() {
                    @Override
                    public void onSuccess() {
                        DebugLogger.d("Entrant", "Entrant created successfully");
                        callback.onSuccess(Entrant.this);
                    }

                    @Override
                    public void onFailure(Exception e) {
                        DebugLogger.d("Entrant", "Entrant creation failed");
                        callback.onFailure(e);
                    }
                });
            }

            @Override
            public void onFailure(Exception e) {
                DebugLogger.d("Entrant", "Entrant creation failed");
            }
        });

    }


    /**
     * Constructor for the Entrant class for creating a primary entrant
     * @param name
     *      Name of the entrant
     * @param email
     *      Email of the entrant
     * @param phoneNumber
     *      Phone number of the entrant
     * @param callback
     *      Callback for when the entrant is created
     */

    public Entrant(String name, String email, String phoneNumber, EntrantCallback callback) {

        this.subEntrants = new ArrayList<Integer>();
        this.organizedEvents = new ArrayList<Integer>();
        EntrantController.getNewEntrantId(new EntrantIDCallback() {
            @Override
            public void onSuccess(int id) {
                Entrant.this.id = id;
                Entrant.this.profile = new Profile(name, email, phoneNumber, true, id);
                EntrantController.writeEntrant(Entrant.this, new DBWriteCallback() {
                    @Override
                    public void onSuccess() {
                        DebugLogger.d("Entrant", "Entrant created successfully");
                        callback.onSuccess(Entrant.this);
                    }

                    @Override
                    public void onFailure(Exception e) {
                        DebugLogger.d("Entrant", "Entrant creation failed");
                        callback.onFailure(e);
                    }
                });
            }

            @Override
            public void onFailure(Exception e) {
                DebugLogger.d("Entrant", "Entrant creation failed");
            }
        });
    }


    /**
     * Constructor for the Entrant class for creating a secondary entrant
     * INCOMPLETE!!
     * @param name
     *      Name of the entrant
     * @param email
     *      Email of the entrant
     * @param phoneNumber
     *      Phone number of the entrant
     * @param parent
     *      Parent of the entrant
     */
    public Entrant(String name, String email, String phoneNumber, Entrant parent, EntrantCallback callback) {
        if (parent.parent != 0 ) {
            throw new IllegalArgumentException("Cant have parent with parent");
        }

        this.subEntrants = null;
        EntrantController.getNewEntrantId(new EntrantIDCallback() {
            @Override
            public void onSuccess(int id) {
                Entrant.this.id = id;
                Entrant.this.profile = new Profile(name, email, phoneNumber, true, id);
                EntrantController.writeEntrant(Entrant.this, new DBWriteCallback() {
                    @Override
                    public void onSuccess() {
                        DebugLogger.d("Entrant", "Entrant created successfully");
                        parent.addSubEntrant(Entrant.this);
                        EntrantController.updateEntrant(parent, new DBWriteCallback() {
                            @Override
                            public void onSuccess() {
                                DebugLogger.d("Entrant", "Parent updated successfully");
                                Entrant.this.parent = parent.getId();
                                callback.onSuccess(Entrant.this);

                            }

                            @Override
                            public void onFailure(Exception e) {
                                DebugLogger.d("Entrant", "Parent update failed");
                            }
                        });

                    }

                    @Override
                    public void onFailure(Exception e) {
                        DebugLogger.d("Entrant", "Entrant write failed");
                    }
                });
            }
            public void onFailure(Exception e) {
                DebugLogger.d("Entrant", "Entrant creation failed");
            }
        });

    }

    /**
     * Test constructor for the Entrant class for creating a secondary entrant
     * @param name
     *      Name of the entrant
     * @param email
     *      Email of the entrant
     * @param phoneNumber
     *      Phone number of the entrant
     * @param id
     *      ID of the entrant
     * @param parent
     *      Parent of the entrant
     */
    public Entrant(String name, String email, String phoneNumber, int id, Entrant parent) {
        if (parent.parent != 0 ) {
            throw new IllegalArgumentException("Cant have parent with parent");
        }
        this.profile = new Profile(name, email, phoneNumber, true, id);
        this.profile.setChangeListener((profile, callback) ->
            entrantModified(callback));

        this.id = id;
        this.parent = parent.getId();
        this.subEntrants = new ArrayList<Integer>();
        parent.addSubEntrant(this);
    }


    /**
     * Getter for the device ID of the entrant
     * @return
     *      Device ID of the entrant
     */
    public String getDeviceId() {
        return deviceId;
    }


    /**
     * Getter for the ID of the entrant
     *
     * @return ID of the entrant
     */
    public int getId() {
        return id;
    }
    /**
     * Getter for the list of sub entrant ids of the entrant
     * @return
     *      List of sub entrant ids of the entrant
     */
    public List<Integer> getSubEntrants() {
        return subEntrants;
    }


    /**
     * Getter for the parent of the entrant
     * @return
     *      Parent of the entrant
     */
    public int getParent() {
        return parent;
    }

    /**
     * Getter for the list of organized events of the entrant
     * @return
     *      List of organized events of the entrant
     */

    public List<Integer> getOrganizedEvents() {
        return organizedEvents;
    }



    /**
     * Setter for the ID of the entrant
     * @param id
     *      ID of the entrant
     */
    public void setId(int id) {
        this.id = id;
        this.profile.setId(id);


    }




    /**
     * Adds a sub entrant to the list of sub entrants of the entrant
     * INCOMPLETE!!
     * @param child
     *      Sub entrant to add
     *
     */
    public void addSubEntrant(Entrant child) {
        subEntrants.add(child.getId());
    }

    /**
     * Adds an organized event to the list of organized events of the entrant
     * @param eventId
     *      Event ID to add
     */
    public void addOrganizedEvent(int eventId) {
        organizedEvents.add(eventId);
    }

    /**
     * Gets the sub entrants of the entrant
     * @param callback
     *      Callback for when the sub entrants are retrieved
     */
    public void getSubEntrants(EntrantListCallback callback) {
        List<Entrant> retSubEntrants = new ArrayList<>();
        for (int i = 0; i < this.subEntrants.size(); i++) {
            int idToGet = this.subEntrants.get(i);
            EntrantController.getEntrant(idToGet, new EntrantCallback() {
                @Override
                public void onSuccess(Entrant entrant) {
                    retSubEntrants.add(entrant);

                    if (retSubEntrants.size() == Entrant.this.subEntrants.size()) {
                        callback.onSuccess(retSubEntrants);
                    }
                }

                @Override
                public void onFailure(Exception e) {
                    callback.onFailure(e);
                }
            });
        }

    }

    /**
     * Gets the parent of the entrant
     * @param callback
     *      Callback for when the parent is retrieved
     */

    public void getParent(EntrantCallback callback) {
        //Get the parent of the entrant
        EntrantController.getEntrant(this.parent, new EntrantCallback() {
            @Override
            public void onSuccess(Entrant entrant) {
                callback.onSuccess(entrant);
            }

            @Override
            public void onFailure(Exception e) {
                callback.onFailure(e);
            }
        });

    }



    /**
     * Checks if two entrants are equal
     * @param o
     *      Object to compare to
     * @return
     *      True if the objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Entrant entrant = (Entrant) o;
        return id == entrant.id; // or whatever uniquely identifies an Entrant
    }
    /**
     * Generates a hash code for the entrant
     * @return
     *      Hash code for the entrant
     */
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    /**
     * Sets the device ID of the entrant
     * @param testDeviceId
     *      Device ID to set
     */

    public void setDeviceId(String testDeviceId) {
        this.deviceId = testDeviceId;


    }

    /**
     * Sets the list of organized events of the entrant
     * @param organizedEvents
     *      List of organized events to set
     */
    public void setOrganizedEvents(List<Integer> organizedEvents) {
        this.organizedEvents = organizedEvents;
    }



    public Profile getProfile() {
        return profile;
    }

    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public void entrantModified(DBWriteCallback callback) {
        EntrantController.updateEntrant(this, callback);
    }


}
