package com.example.slices.models;

import com.example.slices.interfaces.DBWriteCallback;
import com.example.slices.interfaces.ProfileChangeListener;

public class Profile {
    /**
     * Name of the entrant
     */
    private String name;
    /**
     * Email of the entrant, may be null
     */
    private String email;
    /**
     * Phone number of the entrant, may be null
     */
    private String phoneNumber;
    /**
     * Notification preference of entrant, may be null
     */
    private boolean sendNotifications;
    /**
     * ID of the entrant, generated by the database
     */

    private int id;

    private transient ProfileChangeListener changeListener;


    /**
     * Default constructor for the Profile class, need for serialization
     */
    public Profile() {}

    public Profile(String name, String email, String phoneNumber, boolean sendNotifications, int id) {
        this.name = name;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.sendNotifications = sendNotifications;
        this.id = id;

    }

    public Profile(int id) {
        this.id = id;
        this.sendNotifications = true;
    }

    public Profile(String name, String email, String phoneNumber, int id) {
        this.name = name;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.sendNotifications = true;
        this.id = id;
    }

    public String getName() {
        return name;
    }
    public String getEmail() {
        return email;
    }
    public String getPhoneNumber() {
        return phoneNumber;
    }
    public boolean getSendNotifications() {
        return sendNotifications;
    }
    public int getId() {
        return id;
    }


    public void updateProfile(String name, String email, String phoneNumber, boolean sendNotifications, DBWriteCallback callback) {
        if (name != null) {
            this.name = name;
        }
        if (email != null) {
            this.email = email;
        }
        if (phoneNumber != null) {
            this.phoneNumber = phoneNumber;
        }
        this.sendNotifications = sendNotifications;
        notifyChange(callback);
    }
    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * Do NOT call this method directly. Use the update counterpart instead.
     * @param name
     *      Name to set
     */
    @Deprecated
    public void setName(String name) {
        this.name = name;
    }

    public void updateName(String name, DBWriteCallback callback) {
        this.name = name;
        notifyChange(callback);

    }

    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * Do NOT call this method directly. Use the update counterpart instead.
     * @param email
     *      Email to set
     */
    @Deprecated
    public void setEmail(String email) {
        this.email = email;
    }

    public void updateEmail(String email, DBWriteCallback callback) {
        this.email = email;
        notifyChange(callback);

    }

    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * Do NOT call this method directly. Use the update counterpart instead.
     * @param phoneNumber
     *      Phone number to set
     */
    @Deprecated
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Updates the phone number of the entrant
     * @param phoneNumber
     *      New phone number
     * @param callback
     *      Callback for database write completion
     */
    public void updatePhoneNumber(String phoneNumber, DBWriteCallback callback) {
        this.phoneNumber = phoneNumber;
        notifyChange(callback);

    }

    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * Do NOT call this method directly. Use the update counterpart instead.
     * @param sendNotifications
     *      Notification preference to set
     */
    @Deprecated
    public void setSendNotifications(boolean sendNotifications) {
        this.sendNotifications = sendNotifications;
    }

    public void updateSendNotifications(boolean sendNotifications, DBWriteCallback callback) {
        this.sendNotifications = sendNotifications;
        notifyChange(callback);
    }

    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * Do NOT call this method directly. Use the update counterpart instead.
     * @param id
     */
    @Deprecated
    public void setId(int id) {
        this.id = id;
    }

    public void setChangeListener(ProfileChangeListener changeListener) {
        this.changeListener = changeListener;
    }

    public void notifyChange(DBWriteCallback callback) {
        if (changeListener != null) {
            changeListener.onProfileChanged(this, callback);
        }
        else {
            callback.onFailure(new Exception("No change listener set"));
        }
    }



}
