package com.example.slices.models;

import com.example.slices.interfaces.DBWriteCallback;

public class Profile {
    /**
     * Name of the entrant
     */
    private String name;
    /**
     * Email of the entrant, may be null
     */
    private String email;
    /**
     * Phone number of the entrant, may be null
     */
    private String phoneNumber;
    /**
     * Notification preference of entrant, may be null
     */
    private boolean sendNotifications;
    /**
     * ID of the entrant, generated by the database
     */

    private int id;


    /**
     * Default constructor for the Profile class, need for serialization
     */
    public Profile() {}

    public Profile(String name, String email, String phoneNumber, boolean sendNotifications, int id) {
        this.name = name;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.sendNotifications = sendNotifications;
        this.id = id;

    }

    public Profile(int id) {
        this.id = id;
        this.sendNotifications = true;
    }

    public Profile(String name, String email, String phoneNumber, int id) {
        this.name = name;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.sendNotifications = true;
        this.id = id;
    }

    public String getName() {
        return name;
    }
    public String getEmail() {
        return email;
    }
    public String getPhoneNumber() {
        return phoneNumber;
    }
    public boolean getSendNotifications() {
        return sendNotifications;
    }
    public int getId() {
        return id;
    }


    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * @param name
     *      Name to set
     */

    public void setName(String name) {
        this.name = name;
    }


    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * @param email
     *      Email to set
     */

    public void setEmail(String email) {
        this.email = email;
    }



    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * @param phoneNumber
     *      Phone number to set
     */

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }




    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * @param sendNotifications
     *      Notification preference to set
     */

    public void setSendNotifications(boolean sendNotifications) {
        this.sendNotifications = sendNotifications;
    }


    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * @param id
     *      ID to set
     */

    public void setId(int id) {
        this.id = id;
    }





}
