package com.example.slices.models;


public class Profile {
    /**
     * Name of the entrant
     */
    private String name;
    /**
     * Email of the entrant, may be null
     */
    private String email;
    /**
     * Phone number of the entrant, may be null
     */
    private String phoneNumber;
    /**
     * Notification preference of entrant, may be null
     */
    private boolean sendNotifications;
    /**
     * ID of the entrant, generated by the database
     */

    private int id;

    //private (Something) location


    /**
     * Default constructor for the Profile class, need for serialization
     */
    public Profile() {}

    public Profile(String name, String email, String phoneNumber, boolean sendNotifications, int id) {
        this.name = name;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.sendNotifications = sendNotifications;
        this.id = id;
    }


    /**
     * Constructor for the Profile class that only sets the ID
     * @param id
     *      ID of the entrant
     */

    public Profile(int id) {
        this.id = id;
        this.sendNotifications = true;
    }

    /**
     * Constructor for the Profile class that sets all fields
     * @param name
     *      Name of the entrant
     * @param email
     *      Email of the entrant
     * @param phoneNumber
     *      Phone number of the entrant
     * @param id
     *      ID of the entrant
     */
    public Profile(String name, String email, String phoneNumber, int id) {
        this.name = name;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.sendNotifications = true;
        this.id = id;
    }

    /**
     * Getter for the name of the entrant
     * @return
     *      Name of the entrant
     */
    public String getName() {
        return name;
    }

    /**
     * Getter for the email of the entrant
     * @return
     *      Email of the entrant
     */
    public String getEmail() {
        return email;
    }

    /**
     * Getter for the phone number of the entrant
     * @return
     *      Phone number of the entrant
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Getter for the entrant's notification preference
     * @return
     *      True if the entrant has notifications enabled
     */
    public boolean getSendNotifications() {
        return sendNotifications;
    }

    /**
     * Getter for the ID of the entrant
     * @return
     *      ID of the entrant
     */
    public int getId() {
        return id;
    }


    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * @param name
     *      Name to set
     */
    public void setName(String name) {
        this.name = name;
    }


    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * @param email
     *      Email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }


    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * @param phoneNumber
     *      Phone number to set
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }


    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * @param sendNotifications
     *      Notification preference to set
     */
    public void setSendNotifications(boolean sendNotifications) {
        this.sendNotifications = sendNotifications;
    }


    /**
     * INTERNAL USE ONLY - Firestore requires this setter
     * @param id
     *      ID to set
     */
    public void setId(int id) {
        this.id = id;
    }



}
